variables:
  # Don't download unneeded packages
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: 'true'
  # Improve performance by not sending telemetry
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 'true'

trigger:
  branches:
    include:
      - release/*

resources:
  repositories:
  - repository: ComplianceRepo
    type: github
    endpoint: ComplianceGHRepo
    name: PowerShell/Compliance
  pipelines:
  - pipeline: PowerShellEditorServices
    source: PowerShellEditorServices
    trigger:
      branches:
        include:
        - release/*
      tags:
      - v*

jobs:
- job: 'ReleaseBuild'
  displayName: 'Build release'
  pool:
    name: '1ES'
    demands: ImageOverride -equals MMS2019
  variables:
  - group: ESRP
  steps:
  - template: templates/release-general.yml
